FROM ghcr.io/jhwohlgemuth/jupyter:latest

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

EXPOSE 1337
EXPOSE 8888
#
# Install .NET (C#, F#, and PowerShell) kernels
#
WORKDIR /root
ENV PATH "${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global Microsoft.dotnet-interactive \
    && dotnet interactive jupyter install

WORKDIR /root/dev/notebooks
ENTRYPOINT ["/root/miniconda3/bin/conda", "run", "-n", "base", "jupyter"]
CMD ["notebook", "--allow-root", "--Session.debug=True"]