FROM ubuntu:focal

LABEL author="Jason Wohlgemuth"

EXPOSE 4669

ENV TZ America/Chicago

# Install dependencies
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install --no-install-recommends -y \
    apt-utils \
    build-essential \
    ca-certificates \
    curl \
    git \
    libssl-dev \
    openssh-server \
    pkg-config \
    tzdata \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
ENV PATH "/root/bin:${PATH}"
ENV NVM_DIR "/root/.nvm"
RUN echo ". ${NVM_DIR}/nvm.sh" >> ~/.bashrc

# Install rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH "/root/.cargo/bin:${PATH}"
RUN rustup toolchain install nightly \
    && rustup target add wasm32-unknown-unknown --toolchain nightly
RUN cargo install wasm-bindgen-cli \
    && cargo install wasm-pack

ENTRYPOINT [ "/bin/bash" ]