FROM ghcr.io/jhwohlgemuth/jupyter:latest

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

EXPOSE 1337
EXPOSE 8888
#
# Install R language and kernel
#
RUN apt-get update && apt-get install --no-install-recommends -y \
        r-base \
    && apt-get clean \
    && rm -rf \
        /tmp/* \
        /var/lib/apt/lists/* \
        /var/tmp/* \
    # Configure R
    && R -e "install.packages(c('formatR', 'jsonlite'), repos='http://cran.rstudio.com')" \
    # Install R kernel
    && R -e "install.packages('IRkernel')" && R -e "IRkernel::installspec()"
#
# Install Perfomant Python tools, Python alternatives, and Coq kernel
#
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir \
        hy \
        jill \
        # pyjion \
    # Install Coq kernel
    && pip install --no-cache-dir coq-jupyter && python -m coq_jupyter.install \
    # Install Codon
    && /bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)" \
    && echo 'export PATH="${HOME}/.codon/bin:${PATH}"' >> "${HOME}/.zshrc"
#
# Install Nim language and kernel
#
ENV PATH "${PATH}:/root/.nimble/bin"
RUN curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh \
    && sh init.sh -y \
    && rm init.sh \
    && /root/.nimble/bin/choosenim stable \
    && nimble install jupyternim -y
#
# Install Coq, Julia, and Lua kernels
#
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN jill install --confirm && julia -e 'using Pkg;Pkg.add("IJulia")' \
    && mamba install --channel conda-forge --yes \
        coq-jupyter \ 
        xeus-lua
WORKDIR /usr/local/share/jupyter/kernels/coq
COPY ./jupyter/logo_coq.png logo-64x64.png

WORKDIR /root/dev/notebooks
ENTRYPOINT ["/root/miniconda3/bin/conda", "run", "-n", "base", "jupyter"]
CMD ["notebook", "--allow-root", "--Session.debug=True"]