FROM ghcr.io/jhwohlgemuth/jupyter:latest

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

EXPOSE 4669
#
# Install Java, Scala, and Kotlin
#
SHELL ["/bin/bash", "-c"]
RUN curl -s "https://get.sdkman.io" | bash \
    && source "${HOME}/.sdkman/bin/sdkman-init.sh" \
    && yes | sdk install java 18-open \
    && yes | sdk install scala \
    && yes | sdk install kotlin \
    && yes | sdk install leiningen \
    && rm -rf "${HOME}/.sdkman/archives/*" \
    && rm -rf "${HOME}/.sdkman/tmp/*"
# Install Clojure language
#
SHELL ["/bin/sh", "-c"]
RUN curl -O https://download.clojure.org/install/linux-install-1.10.1.561.sh \
    && chmod +x linux-install-1.10.1.561.sh \
    && ./linux-install-1.10.1.561.sh \
    && mkdir /root/.lein
COPY ./config/profiles.clj /root/.lein/
#
# Install Clojure kernel
#
WORKDIR /root
RUN git clone https://github.com/clojupyter/clojupyter.git
WORKDIR /root/clojupyter
RUN git checkout master && git submodule update --init
ENV PATH "${PATH}:/root/.sdkman/candidates/leiningen/current/bin:/root/.sdkman/candidates/java/current/bin/"
RUN git checkout 0.2.2 \
    && make install \
    && cd .. \
    && rm -rf clojupyter
WORKDIR /root/.local/share/jupyter/kernels/clojupyter
COPY ./jupyter/logo_clojure.png logo-64x64.png
#
# Install Scala kernel
#
WORKDIR /opt
RUN curl -Lo coursier https://git.io/coursier-cli \
    && chmod +x coursier \
    && ./coursier launch --fork almond:0.11.1 --scala 2.13 -- --install \
    && rm -f coursier
#
# Install Kotlin kernel
#
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir \
        kotlin-jupyter-kernel

WORKDIR /root/dev/notebooks
ENTRYPOINT ["/root/miniconda3/bin/conda", "run", "-n", "base", "jupyter"]
CMD ["notebook", "--allow-root", "--Session.debug=True"]