ARG BASE=ubuntu
ARG TAG=focal
ARG IMAGE=$BASE:$TAG
FROM $IMAGE

LABEL author="Jason Wohlgemuth"

EXPOSE 1337 4669 8000 8080 8111 46692

ENV TZ America/New_York
ENV TERM xterm-256color
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#
# Install system dependencies
#
WORKDIR /root
ARG DEBIAN_FRONTEND=noninteractive
COPY ./dev-with-docker/provision/install_dependencies.sh .
RUN chmod +x ./install_dependencies.sh \
    && ./install_dependencies.sh \
    && rm ./install_dependencies.sh
#
# Install and configure oh-my-zsh
#
WORKDIR /root
ARG DEBIAN_FRONTEND=noninteractive
COPY ./dev-with-docker/provision/install_ohmyzsh.sh .
RUN chmod +x ./install_ohmyzsh.sh \
    && ./install_ohmyzsh.sh \
    && rm ./install_ohmyzsh.sh
#
# Configure NeoVim
#
ENV NEOVIM_ROOT /root/.config/nvim/
COPY ./dev-with-neovim/init.vim $NEOVIM_ROOT
COPY ./dev-with-neovim/coc-settings.json $NEOVIM_ROOT
COPY ./dev-with-neovim/general/settings.vim "${NEOVIM_ROOT}general/"
COPY ./dev-with-neovim/general/plugins.vim "${NEOVIM_ROOT}general/"
COPY ./dev-with-neovim/plug-config/coc.vim "${NEOVIM_ROOT}plug-config/"
COPY ./dev-with-neovim/plug-config/fzf.vim "${NEOVIM_ROOT}plug-config/"
COPY ./dev-with-neovim/plug-config/which-key.vim "${NEOVIM_ROOT}plug-config/"
COPY ./dev-with-neovim/themes/onedark.vim "${NEOVIM_ROOT}themes/"
RUN find $NEOVIM_ROOT -name "*.vim" | xargs dos2unix

ENTRYPOINT [ "/bin/zsh" ]