FROM ubuntu:focal

LABEL author="Jason Wohlgemuth"

EXPOSE 1337 4669 8000 8080 8111 46692

ENV TZ America/Chicago
ENV TERM xterm-256color

# # Install dependencies
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install --no-install-recommends -y \
    apt-utils \
    apt-transport-https \
    build-essential \
    curl \
    fzf \
    git \
    gnupg \
    httpie \
    jq \
    less \
    libssl-dev \
    nano \
    neovim \
    openssh-server \
    pkg-config \
    python3-pip \
    rlwrap \
    snapd \
    tree \
    tzdata \
    unzip \
    zip \
    zsh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# This addresses a bug in the Rust build tools [link](https://askubuntu.com/a/1300824)
RUN apt-get update && apt-get install --no-install-recommends -y -o Dpkg::Options::="--force-overwrite" \
    bat \
    ripgrep

# # Install and configure oh-my-zsh
RUN sh -c "$(curl https://raw.githubusercontent.com/deluan/zsh-in-docker/master/zsh-in-docker.sh)" -- \
    -p colored-man-pages \
    -p encode64 \
    -p extract \
    -p fzf \
    -p git \
    -p history-substring-search \
    -p wd \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-syntax-highlighting \
    -p https://github.com/jhwohlgemuth/zsh-handy-helpers \
    -p https://github.com/jhwohlgemuth/zsh-pentest \
    -a 'bindkey "\$terminfo[kcuu1]" history-substring-search-up' \
    -a 'bindkey "\$terminfo[kcud1]" history-substring-search-down'
# # Customize .zshrc
RUN sed -i "s/export TERM=xterm/export TERM=xterm-256color/g" ~/.zshrc \
    && echo "ZLE_RPROMPT_INDENT=0" >> ~/.zshrc \
    && echo "alias bat=batcat" >> ~/.zshrc \
    && echo "alias python=python3" >> ~/.zshrc \
    && echo "alias pip=pip3" >> ~/.zshrc

# Configure NeoVim
ENV NEOVIM_ROOT /root/.config/nvim/
COPY ./dev-with-neovim/init.vim $NEOVIM_ROOT
COPY ./dev-with-neovim/coc-settings.json $NEOVIM_ROOT
COPY ./dev-with-neovim/general/settings.vim "${NEOVIM_ROOT}general/"
COPY ./dev-with-neovim/general/plugins.vim "${NEOVIM_ROOT}general/"
COPY ./dev-with-neovim/plug-config/coc.vim "${NEOVIM_ROOT}plug-config/"
COPY ./dev-with-neovim/plug-config/fzf.vim "${NEOVIM_ROOT}plug-config/"
COPY ./dev-with-neovim/plug-config/which-key.vim "${NEOVIM_ROOT}plug-config/"
COPY ./dev-with-neovim/themes/onedark.vim "${NEOVIM_ROOT}themes/"

ENTRYPOINT [ "/bin/zsh" ]