FROM ghcr.io/jhwohlgemuth/notebook:latest

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

EXPOSE 1337
EXPOSE 13337
#
# Install .NET (C#, F#, and PowerShell) kernels
#
WORKDIR /root
ENV PATH "${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global Microsoft.dotnet-interactive \
    && dotnet interactive jupyter install

WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]