FROM ghcr.io/jhwohlgemuth/notebook:latest

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

EXPOSE 1337
EXPOSE 13337
#
# Install R language and kernel
#
# hadolint ignore=DL3009
RUN apt-get update && apt-get install --no-install-recommends -y r-base \
    && mamba install --channel conda-forge --yes radian \
    && mamba clean -yaf \
    && echo 'alias r=radian' >> "${HOME}/.zshrc" \
    && R -e "install.packages(c('formatR', 'jsonlite'), repos='http://cran.rstudio.com')" \
    && R -e "install.packages('IRkernel')" && R -e "IRkernel::installspec()"
#
# Install Julia language and kernel
#
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN curl -fsSL https://install.julialang.org | sh -s -- --yes \
    && source "${HOME}/.bashrc" \
    && juliaup add 1.6.7 \
    && juliaup default 1.6.7 \
    && julia -e 'using Pkg;Pkg.add("IJulia")'
#
# Install Lua language and kernel
#
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN /home/linuxbrew/.linuxbrew/bin/brew install lua luarocks \
    && eval "$(luarocks path)" \
    && mamba install --channel conda-forge --yes xeus-lua \
    && mamba clean -yaf
#
# Install Nim language and kernel
#
WORKDIR /root
SHELL ["/bin/bash", "-c"]
COPY ./provision/scripts/install_nim.sh .
RUN apt-get update && apt-get install --no-install-recommends -y libzmq5 \
    && chmod +x ./install_nim.sh && ./install_nim.sh && rm ./install_nim.sh
#
# Cleanup
#
WORKDIR /root
SHELL ["/bin/bash", "-c"]
RUN cleanup

WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]