FROM ghcr.io/jhwohlgemuth/base:latest

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

# Port designated in ./code-server/config.yaml
EXPOSE 1337
# Port designated in ./jupyter/jupyter_notebook_config.py
EXPOSE 13337

SHELL ["/bin/bash", "-c"]
WORKDIR /root
ENV JUPYTER_ROOT /root/.jupyter
ENV CERTS_DIR /root/certs
RUN mkdir -p /root/dev/notebooks \
    && mkdir -p "${JUPYTER_ROOT}/custom" \
    && mkdir -p $CERTS_DIR
COPY ./jupyter/jupyter_notebook_config.py $JUPYTER_ROOT
COPY ./jupyter/custom.css "${JUPYTER_ROOT}/custom"
COPY ./jupyter/ca.cnf $CERTS_DIR
WORKDIR $CERTS_DIR
RUN openssl req -new -x509 -days 365 -out my.pem -config ca.cnf
WORKDIR /root
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN mamba install --name base --channel conda-forge \
        autopep8 \
        ipykernel \
        ipyparallel \
        manim \
        nb_conda_kernels \
    && mamba clean -yaf
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir \
        ipychart \
        ipyflow \
        jpterm \
        jupyter \
        jupyterlab \
        jupyter_contrib_nbextensions \
        jupyter-tabnine \
        mitosheet \
        # Turtle
        mobilechelonian \
        nbterm \
        yapf \
    && pip install --upgrade --no-cache-dir Pygments \
    #
    # Install and configure Jupyter extensions
    #
    && jupyter contrib nbextension install --user \
    && jupyter nbextension install --py --user jupyter_tabnine \
    && jupyter nbextension enable --py --user jupyter_tabnine \
    && jupyter serverextension enable --py --user jupyter_tabnine
#
# Install code-server (VS Code)
#
WORKDIR /root
ENV PATH "${PATH}:/app/code-server/bin"
ENV CODE_SERVER_CONFIG_DIR /app/code-server/config
COPY ./code-server/settings.json /app/code-server/config/data/Machine/settings.json
COPY ./code-server/config.yaml /app/code-server/config/config.yaml
COPY ./code-server/service/* /etc/services.d/code-server/
COPY ./jupyter/service/* /etc/services.d/jupyter/
COPY ./provision/scripts/install_code_server.sh .
RUN chmod +x ./install_code_server.sh \
    && ./install_code_server.sh \
    && rm ./install_code_server.sh
#
# Copy script to install code-server extensions
#
WORKDIR /usr/local/bin
COPY ./code-server/install_extensions .
RUN chmod +x ./install_extensions

WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]