FROM ghcr.io/jhwohlgemuth/notebook:latest

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

EXPOSE 1337
EXPOSE 13337
#
# Install R language and kernel
#
RUN apt-get update && apt-get install --no-install-recommends -y \
        coq \
        r-base \
    && apt-get clean \
    && rm -rf \
        /tmp/* \
        /var/lib/apt/lists/* \
        /var/tmp/* \
    && mamba install --channel conda-forge --yes radian \
    && mamba clean -yaf \
    && echo 'alias r=radian' >> "${HOME}/.zshrc" \
    && R -e "install.packages(c('formatR', 'jsonlite'), repos='http://cran.rstudio.com')" \
    && R -e "install.packages('IRkernel')" && R -e "IRkernel::installspec()"
#
# Install Briefcase, perfomant Python tools, and Python alternatives
#
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir \
        briefcase \
        hy \
        jill \
        # pyjion \
    # Install Codon
    && /bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)" \
    && echo 'export PATH="${HOME}/.codon/bin:${PATH}"' >> "${HOME}/.zshrc"
#
# Install Nim language and kernel
#
ENV PATH "${PATH}:/root/.nimble/bin"
RUN curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh \
    && sh init.sh -y \
    && rm init.sh \
    && /root/.nimble/bin/choosenim stable \
    && nimble install jupyternim -y
#
# Install Lua language and kernel
#
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN /home/linuxbrew/.linuxbrew/bin/brew install lua luarocks \
    && eval "$(luarocks path)" \
    && mamba install --channel conda-forge --yes xeus-lua \
    && mamba clean -yaf
#
# Install Julia kernel
#
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN jill install --confirm && julia -e 'using Pkg;Pkg.add("IJulia")'
#
# Install Coq kernel
#
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN mamba create --name coq --channel conda-forge --yes coq-jupyter=1.6.0 python=3.10 \
    && mamba clean -yaf
WORKDIR /usr/local/share/jupyter/kernels/coq
COPY ./jupyter/logo_coq.png logo-64x64.png

WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]