FROM ghcr.io/jhwohlgemuth/notebook:latest

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

EXPOSE 1337
EXPOSE 13337
#
# Install Rust language and Jupyter kernel
#
SHELL ["/bin/bash", "-c"]
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH "${PATH}:/root/.cargo/bin"
RUN rustup toolchain install nightly \
    && cargo install \
        evcxr_repl \
        evcxr_jupyter \
    && evcxr_jupyter --install
#
# Copy install scripts
#
WORKDIR /usr/local/bin
COPY ./provision/scripts/install_wasm_runtimes.sh install_wasm_runtimes
RUN chmod +x ./install_wasm_runtimes
#
# Cleanup
#
WORKDIR /root
SHELL ["/bin/bash", "-c"]
COPY ./provision/scripts/cleanup.sh .
RUN chmod +x ./cleanup.sh \
    && ./cleanup.sh \
    && rm ./cleanup.sh

WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]