FROM ghcr.io/jhwohlgemuth/notebook:latest
#
# %labels
#
LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source=https://github.com/jhwohlgemuth/env
#
# %environment
#
EXPOSE 1337
EXPOSE 13337
ENV PATH="${PATH}:/root/.cargo/bin"
#
# %files
#
COPY ./provision/scripts/install_wasm_runtimes.sh /usr/local/bin/install_wasm_runtimes
#
# %post
#
SHELL ["/bin/bash", "-c"]
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y \
    && rustup toolchain install nightly \
    && cargo install \
        evcxr_repl \
        evcxr_jupyter \
    && evcxr_jupyter --install \
    && chmod +x /usr/local/bin/install_wasm_runtimes \
    && cleanup
#
# %runscript
#
WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]