ARG BASE=bitnami/minideb
ARG TAG=bullseye
ARG IMAGE=$BASE:$TAG
FROM $IMAGE
#
# %labels
#
LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source=https://github.com/jhwohlgemuth/env
#
# %arguments
#
ARG HOME=/root
ARG DEBIAN_FRONTEND=noninteractive
#
# %environment
#
ENV TZ=America/New_York
ENV TERM=xterm-256color
ENV NEOVIM_ROOT="${HOME}/.config/nvim/"
ENV PATH="${PATH}:${HOME}/.nix-profile/bin"
ENV PATH="${PATH}:/usr/local/bin/fn"
#
# %setup
#
SHELL ["/bin/bash", "-c"]
RUN ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone \
    && echo "C.utf8 UTF-8" > /etc/locale.gen \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && mkdir -p \
        tmp/scripts \
        /usr/local/bin/fn
#
# %files
#
COPY ./provision/scripts/dev/* /tmp/scripts
COPY ./provision/functions/* /usr/local/bin/fn
COPY ./config/.p10k.zsh "${HOME}/.p10k.zsh"
COPY ./config/profile.ps1 "${HOME}/profile.ps1"
COPY ./config/.theme.omp.json "${HOME}/.theme.omp.json"
COPY ./provision/neovim/init.vim "${NEOVIM_ROOT}"
COPY ./provision/neovim/coc-settings.json "${NEOVIM_ROOT}"
COPY ./provision/neovim/general/settings.vim "${NEOVIM_ROOT}general/"
COPY ./provision/neovim/general/plugins.vim "${NEOVIM_ROOT}general/"
COPY ./provision/neovim/plug-config/coc.vim "${NEOVIM_ROOT}plug-config/"
COPY ./provision/neovim/plug-config/fzf.vim "${NEOVIM_ROOT}plug-config/"
COPY ./provision/neovim/plug-config/which-key.vim "${NEOVIM_ROOT}plug-config/"
COPY ./provision/neovim/themes/onedark.vim "${NEOVIM_ROOT}themes/"
#
# %post
#
SHELL ["/bin/bash", "-c"]
RUN chmod +x /tmp/scripts/* && chmod +x /usr/local/bin/fn/* \
    && /tmp/scripts/install_dependencies.sh \
    && /tmp/scripts/install_dotnet.sh \
    && /tmp/scripts/install_ohmyzsh.sh \
    && /tmp/scripts/install_homebrew.sh \
    && /tmp/scripts/install_apptainer.sh \
    && /tmp/scripts/install_nix.sh \
    && nix-env --install --file /tmp/scripts/manifest.nix \
    && /usr/bin/pwsh -Command /tmp/scripts/Install-OhMyPosh.ps1 \
    && find "${NEOVIM_ROOT}" -name "*.vim" | xargs dos2unix \
    && /tmp/scripts/configure_ohmyzsh.sh
#
# Install s6-overlay and symlinks
#
SHELL ["/bin/bash", "-c"]
ARG S6_OVERLAY_VERSION=3.1.5.0
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-arch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-symlinks-noarch.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-symlinks-arch.tar.xz
#
# Cleanup
#
SHELL ["/bin/bash", "-c"]
RUN cleanup
#
# %runscript
#
WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]