FROM ghcr.io/jhwohlgemuth/dev:latest
#
# %labels
#
LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source=https://github.com/jhwohlgemuth/env
#
# %arguments
#
ARG HOME=/root
ARG MAMBA_VERSION=23.3.1-1
#
# %environment
#
EXPOSE 1337
EXPOSE 13337
ENV CONDA_DIR=/opt/conda
ENV CERTS_DIR="${HOME}/certs"
ENV JUPYTER_ROOT="${HOME}/.jupyter"
ENV JUPYTER_LAB_ROOT=/opt/conda/share/jupyter/lab
ENV CODE_SERVER_CONFIG_DIR=/app/code-server/config
ENV PATH="${PATH}:${CONDA_DIR}/bin"
ENV PATH="${PATH}:/app/code-server/bin"
#
# %setup
#
SHELL ["/bin/bash", "-c"]
RUN mkdir -p \
    /tmp/scripts \
    "${HOME}/dev/notebooks" \
    "${CERTS_DIR}" \
    "${JUPYTER_ROOT}/custom" \
    "${JUPYTER_LAB_ROOT}/settings" \
    /app/code-server/config/data/Machine
#
# %files
#
COPY ./jupyter/ca.cnf "${CERTS_DIR}"
COPY ./jupyter/custom.css "${JUPYTER_ROOT}/custom"
COPY ./jupyter/jupyter_notebook_config.py "${JUPYTER_ROOT}"
COPY ./jupyter/overrides.json "${JUPYTER_LAB_ROOT}/settings"
COPY ./jupyter/service/* /etc/services.d/jupyter/
COPY ./jupyter/environment.yml /tmp/
COPY ./code-server/config.yaml /app/code-server/config/
COPY ./code-server/settings.json /app/code-server/config/data/Machine/
COPY ./code-server/service/* /etc/services.d/code-server/
COPY ./code-server/install_extensions.sh /usr/local/bin/install_extensions
COPY ./provision/scripts/install_conda.sh /tmp/scripts/
COPY ./provision/scripts/install_code_server.sh /tmp/scripts/
#
# %post
#
SHELL ["/bin/bash", "-c"]
RUN chmod +x /tmp/scripts/* && /tmp/scripts/install_conda.sh
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN openssl req -new -x509 -days 365 -out "${CERTS_DIR}/my.pem" -config "${CERTS_DIR}/ca.cnf" \
    && mv "$(pwd)/my.key" "${CERTS_DIR}" \
    && mamba env update --file /tmp/environment.yml \
    && mamba clean -yaf \
    && jupyter contrib nbextension install --user \
    && chmod +x \
        /etc/services.d/jupyter/run \
        /etc/services.d/jupyter/finish \
        /etc/services.d/code-server/run \
        /etc/services.d/code-server/finish \
        /usr/local/bin/install_extensions \
    && /tmp/scripts/install_code_server.sh \
    && cleanup
#
# %startscript
#
WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]