FROM ghcr.io/jhwohlgemuth/rust:latest as build

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

EXPOSE 1337
EXPOSE 13337
#
# Install WebAssembly runtimes
#
SHELL ["/bin/bash", "-c"]
RUN curl https://wasmtime.dev/install.sh -sSf | bash \
    && echo 'export WASMTIME_HOME="${HOME}/.wasmtime"' >> "${HOME}/.zshrc" \
    && echo 'export PATH="${WASMTIME_HOME}/bin:${PATH}"' >> "${HOME}/.zshrc" \
    # WasmEdge
    && curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash \
    && echo '. "${HOME}/.wasmedge/env"' >> "${HOME}/.zshrc" \
    # https://scale.sh
    && curl -fsSL https://dl.scale.sh | sh
#
# Install WASM Workers Server
#
SHELL ["/bin/bash", "-c"]
WORKDIR /usr/local/bin
RUN curl -fsSL https://workers.wasmlabs.dev/install | bash -s -- --local
#
# Install Spin Microservices server
#
SHELL ["/bin/bash", "-c"]
WORKDIR /usr/local/bin
RUN curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash \
    && rm -frd crt.pem LICENSE README.md spin.sig
#
# Install Cosmonic CLI
#
RUN bash -c "$(curl -fsSL https://cosmonic.sh/install.sh)"
#
# Build development image
#
FROM ghcr.io/jhwohlgemuth/rust:latest as dev
#
# Install Rust wasm tooling
#
SHELL ["/bin/bash", "-c"]
RUN rustup target add wasm32-unknown-unknown --toolchain nightly \
    && cargo install \
        wasm-bindgen-cli \
        wasm-pack
COPY --from=build /root/.cosmo /root/.cosmo
COPY --from=build /usr/local/bin/scale /usr/local/bin/scale
COPY --from=build /usr/local/bin/wws /usr/local/bin/wws
COPY --from=build /root/.wasmedge /root/.wasmedge
COPY --from=build /root/.wasmtime /root/.wasmtime
ENV PATH "${PATH}:/root/.cosmo/bin"
RUN echo 'export WASMTIME_HOME="${HOME}/.wasmtime"' >> "${HOME}/.zshrc" \
    && echo 'export PATH="${WASMTIME_HOME}/bin:${PATH}"' >> "${HOME}/.zshrc" \
    && echo '. "${HOME}/.wasmedge/env"' >> "${HOME}/.zshrc"
#
# Install WebAssembly runtimes and WAsmcloud SHell
#
RUN /home/linuxbrew/.linuxbrew/bin/brew install wasmer wapm wasm3 \
    && /home/linuxbrew/.linuxbrew/bin/brew cleanup --prune=all \
    && curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.deb.sh | sudo bash \
    && apt-get install --no-install-recommends -y wash
#
# Cleanup
#
WORKDIR /root
SHELL ["/bin/bash", "-c"]
COPY ./provision/scripts/cleanup.sh .
RUN chmod +x ./cleanup.sh \
    && ./cleanup.sh \
    && rm ./cleanup.sh

WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]
