# syntax=docker/dockerfile:1
ARG BASE=bitnami/minideb
ARG TAG=bullseye
ARG IMAGE=$BASE:$TAG
FROM $IMAGE
#
# %labels
#
LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source=https://github.com/jhwohlgemuth/env
#
# %arguments
#
ARG HOME=/root
ARG DEBIAN_FRONTEND=noninteractive
ARG LANG=en_US.UTF-8
ARG LANGUAGE=en_US:en
ARG LC_ALL=en_US.UTF-8
ARG S6_OVERLAY_VERSION=3.1.5.0
#
# %environment
#
ENV TZ=America/New_York
ENV TERM=xterm-256color
ENV NEOVIM_ROOT="${HOME}/.config/nvim/"
ENV PATH="${PATH}:${HOME}/.nix-profile/bin"
ENV PATH="${PATH}:/usr/local/bin/fn"
#
# %setup
#
SHELL ["/bin/bash", "-c"]
RUN ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime \
    && echo "${TZ}" > /etc/timezone \
    && mkdir -p \
        "${HOME}/.config" \
        "${HOME}/.ssh" \
        /tmp/scripts \
        /usr/local/bin/fn
#
# %files
#
COPY --chmod=0755 ./provision/scripts/dev/* /tmp/scripts
COPY --chmod=0755 ./provision/functions/* /usr/local/bin/fn
COPY ./config/.p10k.zsh "${HOME}/.p10k.zsh"
ADD https://raw.githubusercontent.com/jhwohlgemuth/my-shell-setup/main/config/Microsoft.Powershell_profile.ps1 "${HOME}/profile.ps1"
ADD https://raw.githubusercontent.com/jhwohlgemuth/my-shell-setup/main/config/.theme.omp.json "${HOME}/.theme.omp.json"
ADD https://github.com/jhwohlgemuth/my-neovim-setup.git "${HOME}/.config/nvim/"
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-arch.tar.xz /tmp
#
# %post
#
SHELL ["/bin/bash", "-c"]
RUN /tmp/scripts/install_dependencies.sh \
    && /tmp/scripts/configure_locale.sh \
    && /tmp/scripts/install_dotnet.sh \
    && /tmp/scripts/install_ohmyzsh.sh \
    && /tmp/scripts/install_homebrew.sh \
    && /tmp/scripts/install_apptainer.sh \
    && /tmp/scripts/install_nix.sh && nix-env --install --file /tmp/scripts/manifest.nix \
    && mv /tmp/scripts/install_docker.sh /usr/local/bin/install_docker \
    && /usr/bin/pwsh -Command /tmp/scripts/Install-OhMyPosh.ps1 \
    && /tmp/scripts/configure_ohmyzsh.sh \
    && find "${NEOVIM_ROOT}" -name "*.vim" | xargs dos2unix \
    && tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-symlinks-noarch.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-symlinks-arch.tar.xz \
    && cleanup
#
# %runscript
#
WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]