FROM ghcr.io/jhwohlgemuth/notebook:latest

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

EXPOSE 1337
EXPOSE 13337
#
# Install OCaml kernel
# Note: Needs to be executed first(?)
#
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
WORKDIR /root
RUN apt-get update && apt-get install --no-install-recommends -y \
        ocaml \
        opam \
    && opam init --disable-sandboxing --yes \
    && eval $(opam env) \
    && echo 'eval $(opam env)' >> "${HOME}/.zshrc" \
    && opam install jupyter merlin dune --yes \
    && eval $(opam env) \
    && ocaml-jupyter-opam-genspec \
    && jupyter kernelspec install --name "OCaml" "$(opam var share)/jupyter"
WORKDIR /usr/local/share/jupyter/kernels/ocaml
RUN sed -i 's/OCaml default/OCaml/' kernel.json
COPY ./jupyter/logo_ocaml.png logo-64x64.png
#
# BROKEN Install IHaskell kernel
# 
# SHELL ["/root/miniconda3/bin/conda", "run", "-n", "base", "/bin/bash", "-c"]
# WORKDIR /opt
# RUN git clone https://github.com/gibiansky/IHaskell
# WORKDIR /opt/IHaskell
# ENV PATH "${PATH}:/root/.local/bin"
# RUN curl -sSL https://get.haskellstack.org/ | sh \
#     && pip3 install --no-cache-dir -r requirements.txt \
#     && stack install --fast \
#     && ihaskell install --stack
#
# Cleanup
#
WORKDIR /root
SHELL ["/bin/bash", "-c"]
COPY ./provision/scripts/cleanup.sh .
RUN chmod +x ./cleanup.sh \
    && ./cleanup.sh \
    && rm ./cleanup.sh

WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]