FROM ghcr.io/jhwohlgemuth/notebook:latest

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

EXPOSE 1337
EXPOSE 13337
#
# Install Rust language, libraries, and Jupyter kernel
#
SHELL ["/bin/bash", "-c"]
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH "${PATH}:/root/.cargo/bin"
RUN rustup toolchain install nightly \
    && rustup target add wasm32-unknown-unknown --toolchain nightly \
    && cargo install \
        cargo-audit \
        cargo-edit \
        evcxr_repl \
        wasm-bindgen-cli \
        wasm-pack \
        evcxr_jupyter \
    && evcxr_jupyter --install
#
# Install WebAssembly runtimes
#
SHELL ["/bin/bash", "-c"]
RUN /home/linuxbrew/.linuxbrew/bin/brew install wasmer wapm wasm3 \
    # Wasmtime
    && curl https://wasmtime.dev/install.sh -sSf | bash \
    && echo 'export WASMTIME_HOME="${HOME}/.wasmtime"' >> "${HOME}/.zshrc" \
    && echo 'export PATH="${WASMTIME_HOME}/bin:${PATH}"' >> "${HOME}/.zshrc" \
    # WasmEdge
    && curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash \
    && echo '. "${HOME}/.wasmedge/env"' >> "${HOME}/.zshrc" \
    # https://scale.sh
    && curl -fsSL https://dl.scale.sh | sh
#
# Install WASM Workers Server
#
SHELL ["/bin/bash", "-c"]
WORKDIR /usr/local/bin
RUN curl -fsSL https://workers.wasmlabs.dev/install | bash -s -- --local
#
# Install Spin Microservices server
#
SHELL ["/bin/bash", "-c"]
WORKDIR /usr/local/bin
RUN curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash \
    && rm -frd crt.pem LICENSE README.md spin.sig

WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]