FROM ghcr.io/jhwohlgemuth/notebook:latest

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

EXPOSE 1337
EXPOSE 13337
#
# Install .NET (C#, F#, and PowerShell) kernels
#
WORKDIR /root
ENV PATH "${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global Microsoft.dotnet-interactive \
    && dotnet interactive jupyter install
#
# Install Mono runtime
#
# RUN apt-get update \
#     && apt-get install -y mono-devel \
#     && rm -rf /var/lib/apt/lists/*
RUN gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
    && "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/debian stable-buster main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list \
    && apt-get update && apt-get install --no-install-recommends -y mono-complete
#
# Cleanup
#
WORKDIR /root
SHELL ["/bin/bash", "-c"]
COPY ./provision/scripts/cleanup.sh .
RUN chmod +x ./cleanup.sh \
    && ./cleanup.sh \
    && rm ./cleanup.sh

WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]