FROM ghcr.io/jhwohlgemuth/jupyter:latest

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env

EXPOSE 1337
#
# Install Go
#
SHELL ["/bin/sh", "-c"]
WORKDIR /root
RUN curl -o- https://dl.google.com/go/go1.19.1.linux-amd64.tar.gz | tar -xz -C /usr/local
ENV PATH "${PATH}:/usr/local/go/bin"
#
# Install Go kernel
#
WORKDIR /root
RUN env GO111MODULE=off go get -tags zmq_4_x -d -u github.com/gopherdata/gophernotes \
    && cd "$(go env GOPATH)"/src/github.com/gopherdata/gophernotes \
    && env GO111MODULE=on go install \
    && mkdir -p ~/.local/share/jupyter/kernels/gophernotes \
    && cp kernel/* ~/.local/share/jupyter/kernels/gophernotes
WORKDIR /root/.local/share/jupyter/kernels/gophernotes
RUN chmod +w ./kernel.json \
    && sed "s|gophernotes|$(go env GOPATH)/bin/gophernotes|" < kernel.json.in > kernel.json
#
# Install Ruby
#
SHELL ["/bin/sh", "-c"]
WORKDIR /usr/local/bin
RUN apt-get update && apt-get install --no-install-recommends -y \
        # Ruby
        ruby-full \
    && apt-get clean \
    && rm -rf \
        /tmp/* \
        /var/lib/apt/lists/* \
        /var/tmp/*
#
# Install Swift
#
SHELL ["/bin/bash", "-c"]
ENV SWIFT_SIGNING_KEY 'A62AE125BBBFBB96A6E042EC925CC1CCED3D1561'
ENV SWIFT_PLATFORM 'ubuntu20.04'
ENV SWIFT_BRANCH 'swift-5.5.3-release'
ENV SWIFT_VERSION 'swift-5.5.3-RELEASE'
ENV SWIFT_WEBROOT 'https://download.swift.org'
RUN SWIFT_WEBDIR="${SWIFT_WEBROOT}/${SWIFT_BRANCH}/$(echo ${SWIFT_PLATFORM} | tr -d .)" \
    && SWIFT_BIN_URL="${SWIFT_WEBDIR}/${SWIFT_VERSION}/${SWIFT_VERSION}-${SWIFT_PLATFORM}.tar.gz" \
    && curl -fsSL ${SWIFT_BIN_URL} -o swift.tar.gz \
    && tar -xzf swift.tar.gz --directory / --strip-components=1 \
    && chmod -R o+r /usr/lib/swift \
    && rm -frd swift.tar.gz
#
# Install Swift kernel
#
ENV SWIFT_TENSORFLOW_PATH /usr/lib/swift-tensorflow-toolchain
ENV SWIFT_TENSORFLOW_URL https://storage.googleapis.com/swift-tensorflow-artifacts/releases/v0.13/swift-tensorflow-RELEASE-0.13-ubuntu20.04.tar.gz
WORKDIR ${SWIFT_TENSORFLOW_PATH}
RUN mkdir usr \
    && curl -o swift.tar.gz ${SWIFT_TENSORFLOW_URL} \
    && tar -xzf swift.tar.gz --directory=usr --strip-components=1 \
    && rm swift.tar.gz
WORKDIR /opt
RUN git clone https://github.com/google/swift-jupyter.git
WORKDIR /opt/swift-jupyter
RUN /root/miniconda3/bin/python register.py --user --swift-toolchain ${SWIFT_TENSORFLOW_PATH}
ENV PATH "${PATH}:${SWIFT_TENSORFLOW_PATH}"
WORKDIR /root/.local/share/jupyter/kernels/swift
COPY ./jupyter/logo_swift.png logo-64x64.png 

WORKDIR /root/dev/notebooks
ENTRYPOINT ["/root/miniconda3/bin/conda", "run", "-n", "base", "jupyter"]
CMD ["notebook", "--allow-root", "--Session.debug=True"]