ARG BASE=bitnami/minideb
ARG TAG=bullseye
ARG IMAGE=$BASE:$TAG
FROM $IMAGE

LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source https://github.com/jhwohlgemuth/env
#
# Configure environment variables
#
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ America/New_York
ENV TERM xterm-256color
RUN ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone
ENV CONDA_DIR /opt/conda
ENV NEOVIM_ROOT /root/.config/nvim/
ENV PATH "${PATH}:/usr/local/bin/fn"
ENV PATH "${PATH}:${CONDA_DIR}/bin"
#
# Create folders
#
SHELL ["/bin/bash", "-c"]
RUN mkdir -p /tmp/scripts /usr/local/bin/fn
#
# Copy scripts and functions
#
SHELL ["/bin/bash", "-c"]
COPY ./provision/scripts/dev/* /tmp/scripts
COPY ./provision/functions/* /usr/local/bin/fn
RUN chmod +x /tmp/scripts/* && chmod +x /usr/local/bin/fn/*
#
# Copy confuguration files
#
COPY ./config/.p10k.zsh /root/.p10k.zsh
COPY ./config/profile.ps1 /root/profile.ps1
COPY ./config/.theme.omp.json /root/.theme.omp.json
COPY ./provision/neovim/init.vim "${NEOVIM_ROOT}"
COPY ./provision/neovim/coc-settings.json "${NEOVIM_ROOT}"
COPY ./provision/neovim/general/settings.vim "${NEOVIM_ROOT}general/"
COPY ./provision/neovim/general/plugins.vim "${NEOVIM_ROOT}general/"
COPY ./provision/neovim/plug-config/coc.vim "${NEOVIM_ROOT}plug-config/"
COPY ./provision/neovim/plug-config/fzf.vim "${NEOVIM_ROOT}plug-config/"
COPY ./provision/neovim/plug-config/which-key.vim "${NEOVIM_ROOT}plug-config/"
COPY ./provision/neovim/themes/onedark.vim "${NEOVIM_ROOT}themes/"
#
# Install dependencies
#
SHELL ["/bin/bash", "-c"]
RUN /tmp/scripts/install_dependencies.sh \
    && /tmp/scripts/install_dotnet.sh \
    && /tmp/scripts/install_ohmyzsh.sh \
    && /tmp/scripts/install_homebrew.sh \
    && /tmp/scripts/install_apptainer.sh \
    && /tmp/scripts/install_conda.sh \
    && /tmp/scripts/install_nix.sh
#
# Install oh-my-posh
#
SHELL ["/usr/bin/pwsh", "-Command"]
RUN /tmp/scripts/Install-OhMyPosh.ps1
#
# Format NeoVim files
#
SHELL ["/bin/bash", "-c"]
RUN find $NEOVIM_ROOT -name "*.vim" | xargs dos2unix
#
# Install s6-overlay and symlinks
#
SHELL ["/bin/bash", "-c"]
ARG S6_OVERLAY_VERSION=3.1.5.0
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-arch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-symlinks-noarch.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-symlinks-arch.tar.xz
#
# Cleanup
#
SHELL ["/bin/bash", "-c"]
RUN cleanup

WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]