FROM ghcr.io/jhwohlgemuth/notebook:latest
#
# %labels
#
LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source=https://github.com/jhwohlgemuth/env
#
# %arguments
#
ARG HOME=/root
#
# %environment
#
EXPOSE 1337
EXPOSE 4873
EXPOSE 8080
EXPOSE 13337
ENV NODE_OPTIONS="--max-old-space-size=8192"
ENV PATH="${PATH}:${HOME}/bin"
ENV PATH="${PATH}:${HOME}/.npm-packages/bin"
#
# %setup
#
RUN mkdir -p \
    /tmp/scripts/ \
    /etc/nixos/ \
    /verdaccio/conf/ \
    /etc/services.d/verdaccio/ \
    /verdaccio/conf \
    /verdaccio/plugins \
    /verdaccio/storage
#
# %files
#
COPY ./config/verdaccio/.npmrc "${HOME}/.npmrc"
COPY ./config/verdaccio/config.yml /verdaccio/conf/
COPY ./config/verdaccio/service/* /etc/services.d/verdaccio/
COPY ./provision/scripts/web/manifest.nix /tmp/scripts/
#
# %post
#
SHELL ["/bin/bash", "-c"]
RUN nix-env --install --file /tmp/scripts/manifest.nix \
    && npm install --registry=https://registry.npmjs.org/ --omit=dev --location=global \
        verdaccio \
        rescript@^10.1.4 \
        esy@^0.7.2 \
    && curl -sSL https://get.wasp-lang.dev/installer.sh | sh \
    && chmod +x /etc/services.d/verdaccio/run /etc/services.d/verdaccio/finish
#
# %runscript
#
WORKDIR /root/dev
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]