#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#
# Install Code Server extensions
#
if [ -z "$1" ]
then
    ARGS=notebook
else
    ARGS=("$@")
fi
for ARG in "${ARGS[@]}"; do
    echo "Installing extensions for ${ARG} VS Code instance"
    EXTENSIONS="$(jq -r ".${ARG}[]" "${CODE_SERVER_CONFIG_DIR}"/Extensions.json)"
    for EXTENSION in ${EXTENSIONS}; do
        code-server --extensions-dir "${CODE_SERVER_CONFIG_DIR}/extensions" --install-extension "${EXTENSION}" --force
    done
done