#!/usr/bin/with-contenv bash

CONFIG=${JUPYTER_CONFIG:-/root/.jupyter/jupyter_notebook_config.py}
PORT=${JUPYTER_PORT:-13337}
PASSWORD=${JUPYTER_PASSWORD_HASH:-'argon2:$argon2id$v=19$m=10240,t=10,p=8$bY5rSBCPqjXzzLckWsGTLg$vYg9lyo18FG1kskOrT6ShA'}
sed -i "/c.NotebookApp.port = /c\c.NotebookApp.port = ${PORT}" $CONFIG
sed -i "/c.NotebookApp.password = /c\c.NotebookApp.password = u'${PASSWORD}'" $CONFIG
exec /root/miniconda3/bin/conda run -n base jupyter notebook --allow-root --Session.debug=True