#!/usr/bin/with-contenv bash

CONFIG=${CODE_SERVER_CONFIG:-/app/code-server/config/config.yaml}
PORT=${CODE_SERVER_PORT:-1337}
PASSWORD=${CODE_SERVER_PASSWORD:-password}
sed -i "s/bind-addr: 0.0.0.0:1337/bind-addr: 0.0.0.0:${PORT}/" $CONFIG
sed -i "s/password: password/password: ${PASSWORD}/" $CONFIG
if [ -n "${CODE_SERVER_PASSWORD_HASH}" ]; then
    sed -i "s/password: ${PASSWORD}/hashed-password: ${CODE_SERVER_PASSWORD_HASH}/" $CONFIG
fi
exec /app/code-server/bin/code-server --config $CONFIG ~/dev/notebooks >> /etc/services.d/$1/log