#! /bin/bash

main() {
    local FILE=$NULL
    local EXPRESSION=$NULL
    while getopts 'e:f:btf' OPTCHAR; do
        case "$OPTCHAR" in
            e)
                EXPRESSION="${OPTARG}"
                ;;
            f)
                FILE="${OPTARG}"
                ;;
            b)
                if [ -z "${EXPRESSION}" ]; then
                    echo "==> [Error] -e must be declared before -b" >&2
                    exit 1
                else
                    # shellcheck disable=SC2016
                    EXPRESSION+='{1h;1!H;d};$G'
                fi
                ;;
            t)
                if [ -z "${EXPRESSION}" ]; then
                    echo "==> [Error] -e must be declared before -t" >&2
                    exit 1
                else
                    # shellcheck disable=SC2016
                    EXPRESSION+='!{H;$!d;};${x;s/.//;}'
                fi
                ;;
            ?)
                exit 1
                ;;
        esac
    done
    if [ -z "${FILE}" ]; then
        sed "${EXPRESSION}"
    else
        sed -i "${EXPRESSION}" "${FILE}"
    fi

}
main "$@"