#! /bin/bash

main() {
    local FILE="${1:-$NULL}"
    local EXPRESSION='/^[[:space:]]*$/d'
    if [ -z "${FILE}" ]; then
        sed "${EXPRESSION}"
    else
        sed -i "${EXPRESSION}" "${FILE}"
    fi
}
main "$@"