#! /bin/bash

main() {
    local NC='\033[0m'
    local RED='\033[0;31m'
    if [ -n "$1" ] ; then
        ARGS=("$@")
        for ARG in "${ARGS[@]}"; do
            if [ -f "${ARG}" ] ; then
                continue
            elif is_command "${ARG}" ; then
                continue
            elif is_installed "${ARG}" ; then
                continue
            else
                # shellcheck disable=SC2059
                printf "${RED}==> [ERROR]${NC} ${ARG} not recognized as a command, package, or file\n"
                kill -SIGINT $$
            fi
        done
    fi
}
main "$@"